### ISSUE TITLE
用Django开发这个网站，你用了多久？

### ISSUE THREAD

**Issue by Just2co** [hanyucd/movieweb_python#6]
RT：楼主好，自学Django框架，一两个月能否开发出这种站呢？

**Comment by hanyucd** [comment]
@Just2co  可以了，你可以对着 Django 文档 配合着我的这个应用，敲一遍，跑起来就可以了。
其实，这样学习技术更加有效。我这个写的不难，之前也是初学 django 写的。

**Comment by Just2co** [comment]
@hanyucd 感谢指导，我是看了几遍基础教程，连后面的类，面向对象这些内容都没看，就开始撸requests跟beautifulsoup4，入门了爬虫，基础也增长很多，现在又回过头去看基础教程后面的难点，感觉学习编程还是照着别人的项目代码自己来敲一遍进步最快，光看教程进步很慢，而且很容易忘记。你也是自学的Python吗？之前有没有其他编程基础？现在有没有碰到瓶颈？有没有掉到坑里去过

**Comment by hanyucd** [comment]
@Just2co  嗯，我是自学编程的，最开始就是python 2 入门的，你是学的 2 还是 3？
有遇到瓶颈，我也是学习者呀，可以follow我哟，共同学习。哈哈

**Comment by Just2co** [comment]
好的，咱俩共勉，你有没有技术讨论QQ群，或者微信群，给我加一下，我是听一个技术比较厉害的大牛，跟他在这上面交往几年了，他推荐我学的Python3，现在大部分企业都转到3 了，2很快就会过时，现在刚出来的linux发行版默认的是3了，2会在2020年停止支持。建议你早点转过来，习惯问题而已，print成了函数了，后面要加括号，而且3不用纠结字符编码的问题，非常好用。

**Comment by hanyucd** [comment]
@Just2co 不好意思下午突然有事，这里面有我联系方式：https://github.com/hanyucd/my_resume
